name = "deepfetch-cors-proxy"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# Worker configuration
[env.production]
name = "deepfetch-cors-proxy"

# Optional: Add custom domain later
# routes = [
#   { pattern = "cors-proxy.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
